// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tea_blends.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (
  tea_blend_id,
  name,
  quantity
) VALUES (
  $1, $2, $3
)
RETURNING id, tea_blend_id, name, quantity, created_at, updated_at
`

type CreateLocationParams struct {
	TeaBlendID uuid.UUID
	Name       string
	Quantity   int32
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation, arg.TeaBlendID, arg.Name, arg.Quantity)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.TeaBlendID,
		&i.Name,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeaBlend = `-- name: CreateTeaBlend :one
INSERT INTO tea_blends (
  name,
  description
) VALUES (
  $1, $2
)
RETURNING id, name, description, created_at, updated_at
`

type CreateTeaBlendParams struct {
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateTeaBlend(ctx context.Context, arg CreateTeaBlendParams) (TeaBlend, error) {
	row := q.db.QueryRow(ctx, createTeaBlend, arg.Name, arg.Description)
	var i TeaBlend
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeaBlend = `-- name: DeleteTeaBlend :exec
DELETE FROM tea_blends
WHERE id = $1
`

func (q *Queries) DeleteTeaBlend(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeaBlend, id)
	return err
}

const getTeaBlend = `-- name: GetTeaBlend :one
SELECT id, name, description, created_at, updated_at FROM tea_blends
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTeaBlend(ctx context.Context, id uuid.UUID) (TeaBlend, error) {
	row := q.db.QueryRow(ctx, getTeaBlend, id)
	var i TeaBlend
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeaBlends = `-- name: ListTeaBlends :many
SELECT id, name, description, created_at, updated_at FROM tea_blends
ORDER BY name
`

func (q *Queries) ListTeaBlends(ctx context.Context) ([]TeaBlend, error) {
	rows, err := q.db.Query(ctx, listTeaBlends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeaBlend
	for rows.Next() {
		var i TeaBlend
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocationQuantity = `-- name: UpdateLocationQuantity :one
UPDATE locations
  set quantity = $2,
  updated_at = NOW()
WHERE tea_blend_id = $1
RETURNING id, tea_blend_id, name, quantity, created_at, updated_at
`

type UpdateLocationQuantityParams struct {
	TeaBlendID uuid.UUID
	Quantity   int32
}

func (q *Queries) UpdateLocationQuantity(ctx context.Context, arg UpdateLocationQuantityParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocationQuantity, arg.TeaBlendID, arg.Quantity)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.TeaBlendID,
		&i.Name,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTeaBlend = `-- name: UpdateTeaBlend :one
UPDATE tea_blends
  set name = $2,
  description = $3,
  updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, created_at, updated_at
`

type UpdateTeaBlendParams struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
}

func (q *Queries) UpdateTeaBlend(ctx context.Context, arg UpdateTeaBlendParams) (TeaBlend, error) {
	row := q.db.QueryRow(ctx, updateTeaBlend, arg.ID, arg.Name, arg.Description)
	var i TeaBlend
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
